oracle_databases:                                               # Dictionary describing the databases to be installed
      #- home: 18300-base                                            # 'Last' directory in ORACLE_HOME path (e.g /u01/app/oracle/12.2.0.1/db1)
      #  oracle_db_name: orclcdb                                 # Database name
      #  oracle_db_type: SI                                   # Type of database (RAC,RACONENODE,SI)
      #  is_container: True                                # (true/false) Is the database a container database
      #  storage_type: FS                                     # Database storage to be used. ASM or FS.
      #  oracle_db_mem_totalmb: 1024                            # Amount of RAM to be used for SGA
      #  oracle_database_type: MULTIPURPOSE                   # MULTIPURPOSE|DATA_WAREHOUSING|OLTP
      #  redolog_size: 75M
      #  redolog_groups: 3
      #  datafile_dest: /u02/oradata
      #  recoveryfile_dest: /u02/fra
      #  listener_name: LISTENER                              # This home will have a listener configured
      #  listener_port: 1521
      #  archivelog: False
      #  flashback: False
      #  force_logging: False
      #  state: present
      #  # tablespaces:
      #  #      - { name: users, size: 10M, bigfile: True, autoextend: false , next: 5M, maxsize: 500M, content: permanent, state: present }
      #  init_parameters:
      #       - {name: db_create_file_dest, value: '/u02/oradata', scope: both, state: present}
      #       - {name: db_create_online_log_dest_1, value: '/u02/fra', scope: both, state: present}
      #       - {name: db_recovery_file_dest, value: '/u02/fra', scope: both, state: present}
      #       - {name: db_recovery_file_dest_size, value: 20G, scope: both, state: present}
        # services:
        #      - { name: service2,  state: started }
        # users:
        #   - schema: c##dba
        #     container: all
        #     grants:
        #          - dba
        #     state: present
        
#    - home: db1                                            # 'Last' directory in ORACLE_HOME path (e.g /u01/app/oracle/12.1.0.2/racdb)
#      oracle_version_db: 12.2.0.1                          # Oracle versiono
#      oracle_edition: SE2                                  # The edition of database-server (EE,SE,SEONE,SE2)
#      oracle_db_name: IRIS                                 # Database name
#      oracle_db_passwd: Oracle123                          # Passwords (sys/system/dbsnm etc)
#      oracle_db_sys_passwd: sysboss                        # Passwords (sys specific password)
#      oracle_db_system_passwd: manager10                   # Passwords (system specific password)
#      oracle_db_type: SI                                   # Type of database (RAC,RACONENODE,SI)
#      characterset: WE8ISO8859P1                           # WE8MSWIN1252, AL32UTF8 or other character set
#      is_container: True                                   # (true/false) Is the database a container database
#      pdb_prefix: pdb_IRIS
#      pdb_sys_passwd: manager10pdb                         # Passwords (sys pdbadmin specific password)
#      num_pdbs: 1
#      storage_type: FS                                     # Database storage to be used. ASM or FS.
#      # Specific parameters to be set during installation. Comma-separated list
#      oracle_init_params: db_recovery_file_dest_size=10G,sga_target=1G,sga_max_size=2G,open_cursors=600
#        #processes=600
#      #service_name: orcl_serv                              # Inital service to be created (not in use yet)
#      oracle_db_mem_totalmb: 3072                          # Amount of RAM to be used for SGA + PGA
#      oracle_database_type: MULTIPURPOSE                   # MULTIPURPOSE|DATA_WAREHOUSING|OLTP
#      redolog_size_in_mb: 50
#      listener_name: LISTENER
#      datafile_dest: /u01/app/oracle/oradata
#      recoveryfile_dest: /u01/app/oracle/recovery_area
#      state: present                                        # present | absent


       #- home: db1                                            # 'Last' directory in ORACLE_HOME path (e.g /u01/app/oracle/12.2.0.1/db1)
       #  oracle_version_db: 12.2.0.1                          # Oracle versiono (12.2.0.1,12.1.0.2,12.1.0.1,11.2.0.4,11.2.0.3)
       #  oracle_edition: SE2                                  # The edition of database-server (EE,SE,SEONE)
       #  oracle_db_name: IRIS                                 # Database name
       #  oracle_db_passwd: Oracle123                          # Passwords (sys/system/dbsnm etc)
       #  oracle_db_type: SI                                   # Type of database (RAC,RACONENODE,SI)
       #  is_container: True                                   # (true/false) Is the database a container database
       #  storage_type: FS                                     # Database storage to be used. ASM or FS.
       #  oracle_db_mem_totalmb: 1024                            # Amount of RAM to be used for SGA
       #  oracle_database_type: MULTIPURPOSE                   # MULTIPURPOSE|DATA_WAREHOUSING|OLTP
       #  characterset: WE8ISO8859P1                           # WE8MSWIN1252, AL32UTF8 or other character set
       #  redolog_size_in_mb: 50
       #  datafile_dest: /u01/app/oracle/oradata
       #  recoveryfile_dest: /u01/app/oracle/recovery_area
       #  state: present
       #  pdb_prefix: PDB_
       #  num_pdbs: 1
       #  create_pdb: False
       #  list_pluggable:
       #    - { name: IRIS, usrAdmin: pdbirisadmin, pwdAdmin: qwe123, state: present }         
       #  oracle_init_params: db_recovery_file_dest_size=5G,sga_target=1G,sga_max_size=1G,open_cursors=600,processes=300
       #  #init_parameters:
       #  #     - {name: sga_target, value: 1G, scope: both, state: present}
       #  #     - {name: sga_max_size, value: 2G, scope: both, state: present}
       #  #     - {name: open_cursors, value: 600, scope: both, state: present}
       #  #     - {name: db_create_file_dest, value: '/u01/app/oracle/oradata', scope: both, state: present}
       #  #     - {name: db_recovery_file_dest, value: '/u01/app/oracle/recovery_area', scope: both, state: present}
       #  #     - {name: db_recovery_file_dest_size, value: 5G, scope: both, state: present}

       - home: db1                                            # 'Last' directory in ORACLE_HOME path (e.g /u01/app/oracle/12.2.0.1/db1)
         oracle_version_db: 12.1.0.2                          # Oracle versiono (12.2.0.1,12.1.0.2,12.1.0.1,11.2.0.4,11.2.0.3)
         oracle_edition: EE                                   # The edition of database-server (EE,SE,SEONE)
         oracle_db_name: ICONTLAB                             # Database name
         oracle_db_passwd: oracle0                            # Passwords (sys/system/dbsnm etc)
         oracle_db_type: SI                                   # Type of database (RAC,RACONENODE,SI)
         is_container: True                                   # (true/false) Is the database a container database
         storage_type: FS                                     # Database storage to be used. ASM or FS.
         oracle_db_mem_totalmb: 4096                          # Amount of RAM to be used for SGA
         oracle_database_type: MULTIPURPOSE                   # MULTIPURPOSE|DATA_WAREHOUSING|OLTP
         characterset: AL32UTF8                               # WE8MSWIN1252, AL32UTF8 or other character set
         redolog_size_in_mb: 50
         datafile_dest: /u01/app/oracle/oradata
         recoveryfile_dest: /u01/app/oracle/recovery_area
         state: present
         pdb_prefix: PDB_
         num_pdbs: 1
         create_pdb: False
         list_pluggable:
           - { name: ICONTILAB, usrAdmin: pdbicontilabadmin, pwdAdmin: icontilab0, state: present }         
#         oracle_init_params: db_recovery_file_dest_size=10G,sga_target=2G,sga_max_size=2G,open_cursors=300,processes=300           
         oracle_init_params: db_recovery_file_dest_size=10240,sga_target=2048,sga_max_size=2G,open_cursors=300,processes=300                  #init_parameters:
         #     - {name: sga_target, value: 1G, scope: both, state: present}
         #     - {name: sga_max_size, value: 2G, scope: both, state: present}
         #     - {name: open_cursors, value: 600, scope: both, state: present}
         #     - {name: db_create_file_dest, value: '/u01/app/oracle/oradata', scope: both, state: present}
         #     - {name: db_recovery_file_dest, value: '/u01/app/oracle/recovery_area', scope: both, state: present}
         #     - {name: db_recovery_file_dest_size, value: 5G, scope: both, state: present}
          # services:
         #      - { name: service122,  state: started }
         #users:
         #  - schema: c##dba
         #    container: all
         #    grants:
         #         - dba
         #    state: present


