---
  hostgroup: "{{ group_names[0] }}"
  is_sw_source_local: true
  configure_public_yum_repo: true
  configure_epel_repo: true
  configure_gloginsql: true
  oracle_sw_copy: false
  oracle_sw_unpack: true
  oracle_stage_remote: /nfs/software/orasw
  install_from_nfs: false

  role_separation: false
  device_persistence: asmlib

  configure_interconnect: true
  configure_ssh: true
  configure_host_disks: true

  configure_cluster: true
  install_os_packages: true
  oracle_base: /u01/app/oracle
  old_ssh_config: true
  

################ Grid Infrastructure specifics ################
  oracle_install_version_gi: 12.1.0
  oracle_gi_cluster_type: standard

  oracle_scan: apn-c-vip
  oracle_vip: -vip
  oracle_gi_nic_pub: eth0
  oracle_gi_nic_priv: eth1
  oracle_scan_port: 1521
  oracle_asm_init_dg: crs

  oracle_databases:                                               # Dictionary describing the databases to be installed
        - home: db_1                                              # 'Last' directory in ORACLE_HOME path (e.g /u01/app/oracle/12.1.0.2/racdb)
          oracle_version_db: 12.1.0.2                          # Oracle version
#          oracle_home: /u01/app/oracle/product/12.1.0/db_1     # Oracle home for sw
          oracle_edition: EE                                   # The edition of database-server (EE,SE,SEONE)
          oracle_db_name: apnscoll                             # Database name
#          oracle_db_passwd: W9aAoPzSyV                         # Passwords (sys/system/dbsnm etc)
          oracle_db_type: RAC                                  # Type of database (RAC,RACONENODE,SI,SIFO)
          is_container: true                                # (true/false) Is the database a container database
          pdb_prefix: pd
          num_pdbs: 1
          list_pluggable:
            - { name: apns, usrAdmin: pdapnsadmin, pwdAdmin: y2xaL5VGp0 } 
          storage_type: FS                                     # Database storage to be used. ASM or FS.
          init_parameters:
                 - { name: db_recovery_file_dest_size, value: 100G, state: present, scope: both }
                 - { name: db_recovery_file_dest, value: '/u04/oradata/APN/FRA', state: present, scope: both }
                 - { name: pga_aggregate_target, value: 6G, state: present, scope: both }
                 - { name: pga_aggregate_limit, value: 8G, state: present, scope: both }
#                 - { name: _parallel_statement_queuing, value: "false", state: present, scope: both }
                 - { name: sga_target, value: 6G, state: present, scope: spfile }
                 - { name: sga_max_size, value: 6G, state: present, scope: spfile }
                 - { name: open_cursors, value: 200, state: present, scope: both }
#                 - { name: processes, value: 700, state: present, scope: spfile }
          oracle_db_mem_totalmb: 8192                          # Amount of RAM to be used for SGA
          oracle_database_type: MULTIPURPOSE                   # MULTIPURPOSE|DATA_WAREHOUSING|OLTP
          redolog_size_in_mb: 100
          state: present

 

        # - home: db1                                                   # 'Last' directory in ORACLE_HOME path (e.g /u01/app/oracle/12.1.0.2/racdb)
        #   oracle_version_db: 12.1.0.2                          # Oracle version
        #   oracle_edition: EE                                   # The edition of database-server (EE,SE,SEONE)
        #   oracle_db_name: asmdb12                                 # Database name
        #   oracle_db_passwd: Oracle123                          # Passwords (sys/system/dbsnm etc)
        #   oracle_db_type: RAC                                  # Type of database (RAC,RACONENODE,SI,SIFO)
        #   is_container: true                                # (true/false) Is the database a container database
        #   pdb_prefix: mypdb1
        #   num_pdbs: 1
        #   storage_type: ASM                                     # Database storage to be used. ASM or FS.
        #   init_parameters:
        #          - { name: db_recovery_file_dest_size, value: 4G, state: present, scope: both }
        #          - { name: db_recovery_file_dest, value: '+FRA', state: present, scope: both }
        #          - { name: pga_aggregate_target, value: 500M, state: present, scope: both }
        #          - { name: _parallel_statement_queuing, value: "false", state: present, scope: both }
        #          - { name: sga_target, value: 1G, state: present, scope: spfile }
        #          - { name: sga_max_size, value: 1G, state: present, scope: spfile }
        #          - { name: open_cursors, value: 400, state: present, scope: both }
        #          - { name: processes, value: 700, state: present, scope: spfile }
        #   oracle_db_mem_totalmb: 1024                            # Amount of RAM to be used for SGA
        #   oracle_database_type: MULTIPURPOSE                   # MULTIPURPOSE|DATA_WAREHOUSING|OLTP
        #   redolog_size_in_mb: 100
        #   state: present

  datafile_dest: "/u04/oradata/APN"
  recoveryfile_dest: "/u04/oradata/APN/FRA"

  bck_type_fs: FS                               #type of file system in which put backup rman (AMS|FS)

#  asm_diskgroups:
#    - diskgroup: crs
#      properties:
#        - {redundancy: external, ausize: 4}
#      attributes:
#        - {name: 'compatible.rdbms', value: 11.2.0.4.0}
#        - {name: 'compatible.asm', value: "{{ oracle_install_version_gi }}"}
#      disk:
#        - {device: /dev/sdc, asmlabel: crs01}
#    - diskgroup: data
#      properties:
#        - {redundancy: external, ausize: 4}
#      attributes:
#        - {name: compatible.rdbms, value: 11.2.0.4.0}
#        - {name: compatible.asm, value: "{{ oracle_install_version_gi }}"}
#      disk:
#        - {device: /dev/sdd, asmlabel: data01}
#    - diskgroup: fra
#      properties:
#        - {redundancy: external, ausize: 4}
#      attributes:
#        - {name: compatible.rdbms, value: 11.2.0.4.0}
#        - {name: compatible.asm, value: "{{ oracle_install_version_gi }}"}
#      disk:
#        - {device: /dev/sde, asmlabel: fra01}
#    - diskgroup: acfs
#      properties:
#        - {redundancy: external, ausize: 4}
#      attributes:
#        - {name: compatible.rdbms, value: 11.2.0.4.0}
#        - {name: compatible.asm, value: "{{ oracle_install_version_gi }}"}
#        - {name: compatible.advm, value: "{{ oracle_install_version_gi }}"}
#      disk:
#        - {device: /dev/sdf, asmlabel: acfs01}
#

  expdp_bck_remote_ip: "163.162.24.112"
  expdp_bck_remote_user: "w.curtetti"
  expdp_bck_remote_location: "/BACKUP_DB/COLLAUDO_APNS/"
  expdp_schema_list: 
    - name: "APNS_DEV"
      desc: "APNS Development Environment"
      dbenv: "DEV"
      dbuser: "M2MDEV"
      dbpwd: "M2MDEV0"
      dbconnstr: "APNSCOLL1_BCK"
      dir_archive: "M2MDEV"
      dbfile: "M2MDEV.DEV"
      logfile: "logora_M2MDEV"
    - name: "APNS_M2MTEST"
      desc: "APNS Test Environment Schema M2MTEST"
      dbenv: "TEST"
      dbuser: "M2MTEST"
      dbpwd: "M2MTEST0"
      dbconnstr: "APNSCOLL1_BCK"
      dir_archive: "APNS_M2MTEST"
      dbfile: "M2MTEST.TEST"
      logfile: "logora_M2MTEST"
    - name: "APNS_APNS"
      desc: "APNS Test Environment Schema APNS"
      dbenv: "TEST"
      dbuser: "APNS"
      dbpwd: "APNS0"
      dbconnstr: "APNSCOLL1_BCK"
      dir_archive: "APNS_APNS"
      dbfile: "APNS.TEST"
      logfile: "logora_APNS"
    - name: "ANALYTICS"
      desc: "APNS Test Environment Schema ANALYTICS"
      dbenv: "TEST"
      dbuser: "ANALYTICS"
      dbpwd: "ANALYTICS0"
      dbconnstr: "APNSCOLL1_BCK"
      dir_archive: "ANALYTICS"
      dbfile: "ANALYTICS.TEST"
      logfile: "logora_ANALYTICS"
    - name: "TIDS_M2MTEST"
      desc: "APNS Test Environment Schema TIDS"
      dbenv: "TEST"
      dbuser: "TIDS"
      dbpwd: "TIDS0"
      dbconnstr: "APNSCOLL1_BCK"
      dir_archive: "TIDS_M2MTEST"
      dbfile: "TIDS.TEST"
      logfile: "logora_TIDS"
    - name: "TIDS_APNS"
      desc: "APNS Test Environment Schema TIDS_APNS"
      dbenv: "TEST"
      dbuser: "TIDS_APNS"
      dbpwd: "TIDS_APNS0"
      dbconnstr: "APNSCOLL1_BCK"
      dir_archive: "TIDS_APNS"
      dbfile: "TIDS_APNS.TEST"
      logfile: "logora_TIDS_APNS"

  bck_rman_planning: 
    - name: "full weekly"
      hour: "4"
      minute: "0"
      dow: "0"
      cmd_parameter: "-f"
    - name: "archivelog daily"
      hour: "4"
      minute: "0"
      dow: "1-6"
      cmd_parameter: "-a"
    - name: "maintenance daily"
      hour: "6"
      minute: "0"
      dow: "0-6"
      cmd_parameter: "-m"
 
# vim: ts=2 sw=2 expandtab syntax=yaml
